version: '3.3'
services:
  decadevs_docker:
    container_name: decadevs-docker-francis
    image: decadevs-docker-francis
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: francis
      MYSQL_USER: francis
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: francis